# Database Configuration
db.url = jdbc:mysql://localhost:3306/parking_lot_db
db.username = root
db.password = 1234

# Vehicle Fee / hour
fee.hourly.motorcycle = 10.0
fee.hourly.car = 20.0
fee.hourly.bus = 50.0